version: "3"

name: ${APP_NAME-"viktor-project"}

services:
  server:
    dns: 8.8.8.8
    container_name: ${APP_NAME-"viktor-project"}
    tty: true
    build:
      dockerfile: "${VIKTOR_DOCKER-./.viktor/viktor/Dockerfile.server}"
      context: ${APP_DIR-../../}
      args:
        VIKTOR_ROOT: ${VIKTOR_ROOT-./.viktor/viktor/}
        SERV_NAME: ${SERVER_NAME-localhost}
        MERCURE_KEY: ${MERCURE_JWT_KEY-""}
        MERCURE_ENABLE: ${MERCURE_ENABLE-0}
    ports:
      - "8080:80"
      - "4443:443"
      - "4443:443/udp"
      - "3000:3000"
    volumes:
      - "${APP_DIR-../../}:/app/"
    networks:
      - viktor-network

networks:
  viktor-network:
    external: true
